config/routes.rb
Workspace::Application.routes.draw do
  
  get "static_pages/about"
  get "static_pages/home"
  get "static_pages/contact"
  resources :users
  
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'
 
  
  root 'static_pages#about'
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
        
    validates :email, presence: true, uniqueness: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    
    def new
    end
    
    def create
        @user = User.find_by_email(params[:session][:email])
        
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to root_path, flash: { success: "Welcome back #{@user.name}"}
            
        else
            flash.now[:danger] = 'Invalid email and username'
            render 'new'
        end
        
    end
    
    def destroy
        session.delete(:user_id) if logged_in?
        redirect_to root_path, flash: { success: 'Logged Out!'}
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
  
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            #success
            redirect_to root_path, flash: {success:  'Successfully created account'}
        else
            #fail
            render 'new'
        end
    end
    
    def index
    end
    
    def edit
    end

    
    private
        
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
        @current_user = User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container" id="footer">
    <div class="row">
        <div class="col-xs-12">
            <p>All Content &copy; Fakhitah Ridzuan</p>
        </div>
    </div>
</div>

app/views/layouts/_message.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "alert alert-#{name}" %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-default" role="navigation">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img src="http://icons.iconarchive.com/icons/double-j-design/origami-colored-pencil/256/blue-clock-icon.png" width="77" height="73">
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav pull-right">
         <% if logged_in? %>
                    <li><%= link_to 'Home', static_pages_home_path %> </li>
                    <li><%= link_to 'Sign Out', signout_path, method: :delete %></li>
                    
                    
                    
         <% else %>
                    <li><%= link_to 'About', root_path%></li>
                    <li><%= link_to 'Sign In', signin_path %></li>
        <% end %>
    </ul>
      

    </div><!-- /.navbar-collapse -->
<!-- /.container-fluid -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What Time Is It?</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<%= render 'layouts/message' %>

<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/static_pages/about.html.erb
 <% if logged_in? %>
  

      
                    
 <% else %>
 <div class="jumbotron">
    <div class="container">
      <center><h1>What Time Is It!</h1>
      <p>At WhatTimeIsIt (WTIS), we do what we are best at - provide time for those who want to view the time.</p>
      <p><a class="btn btn-success btn-lg" href="signup" role="button">Sign Up</a></p></center>
      </div>
      </div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>
<i>What Time Is It</i>
<p>Fakhitah Ridzuan</p>
<p>Contact Me :
    <ul>
        <li>Phone : 0133472471</li>
        <li>Email : fakhitah.ridzuan@gmail.com</li>
    </ul>
</p>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Edit Profile</h1>

    <%= render 'new' %>

    <%= link_to "Show", @user %> |
    <%= link_to "Back", users_path %>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-xs-12">
        <div class="page-header">
        <h1>Listing tasks</h1>

        <table>
          <thead>
               <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Since</th>
                <th>Action</th>
               </tr>
         </thead>
         
  <tbody>
    <% @user.each do |user| %>
      <tr>
         <td><%= user.name %></td>
         <td><%= user.email %></td>
         <td><%= user.created_at %></td>
         <td><%= link_to "Show", user_path (user) %></td>
         <td><%= link_to "Edit", edit_user_path(task) %></td>
         <td><%= link_to "Destroy", user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

        
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Sign Up</h1>
        
    <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
    <div class="alert alert-danger">
        <%= error %>
    </div>
    <% end %>
    <% end %>

    </div>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    

    <%= form_for(@user) do |f| %>
    <div class="form-group">
    <div><%= f.label :name %></div>
    <div><%= f.text_field :name , class: 'form-control'%></div>
    <div/>
    <div class="form-group">
    <div><%= f.label :email %></div>
    <div><%= f.text_field :email, class: 'form-control' %></div>
    <div/>
    <div class="form-group">
    <div><%= f.label :password %></div>
    <div><%= f.text_field :password, class: 'form-control' %></div>
    <div/>
    <div class="form-group">
    <div><%= f.label :password_confirmation %></div>
    <div><%= f.text_field :password_confirmation, class: 'form-control' %></div>
    <div/>
    <div>
    <br>
    </div>
    <div class="form-group"><%= f.submit "Sign Up", class: 'btn-btn-default btn-primary' %></div>

<% end %>
    </div>

</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">

<p>
  <strong>Name:</strong>
    <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to "Edit", edit_user_path(@user) %> |
<%= link_to "Back", users_path %>

</div>
</div>